spring:
  application:
    name: eureka-server
    
#server:
#  port: 2001
  
eureka:
  server:
    enable-self-preservation: false
    
#  instance:
#    hostname: eureka1
#  client:
#    register-with-eureka: false
#    fetch-registry: false
    
---
#eureka:
#  instance:
#    hostname: eureka1
#  client:
#    register-with-eureka: true  #profile的配置会覆盖公用配置
#    fetch-registry: true        #profile的配置会覆盖公用配置
#    service-url: 
#      defaultZone: http://eureka2:2002/eureka  #eureka1启动时向eureka2注册

spring:
  profiles: eureka1

server:  port: 2001

eureka:
  instance:    hostname: eureka1
  client:    service-url: 
      defaultZone: http://eureka:2002/eureka
---
#eureka:
#  instance:
#    hostname: eureka2
#  client:
#    register-with-eureka: true  #profile的配置会覆盖公用配置
#    fetch-registry: true        #profile的配置会覆盖公用配置
#    service-url: 
#      defaultZone: http://eureka1:2001/eureka  #eureka2启动时向eureka1注册

spring:
  profiles: eureka2

server:
  port: 2002

eureka:
  instance:
    hostname: eureka2
  client:
    service-url: 
      defaultZone: http://eureka:2001/eureka
